package com.gppdi.ubipri.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gppdi.ubipri.dao.Environment;
import com.gppdi.ubipri.dao.LocalizationType;
import com.gppdi.ubipri.dao.Environment;

import com.gppdi.ubipri.dao.EnvironmentDao;
import com.gppdi.ubipri.dao.LocalizationTypeDao;
import com.gppdi.ubipri.dao.EnvironmentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig environmentDaoConfig;
    private final DaoConfig localizationTypeDaoConfig;
    private final DaoConfig environmentDaoConfig;

    private final EnvironmentDao environmentDao;
    private final LocalizationTypeDao localizationTypeDao;
    private final EnvironmentDao environmentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        environmentDaoConfig = daoConfigMap.get(EnvironmentDao.class).clone();
        environmentDaoConfig.initIdentityScope(type);

        localizationTypeDaoConfig = daoConfigMap.get(LocalizationTypeDao.class).clone();
        localizationTypeDaoConfig.initIdentityScope(type);

        environmentDaoConfig = daoConfigMap.get(EnvironmentDao.class).clone();
        environmentDaoConfig.initIdentityScope(type);

        environmentDao = new EnvironmentDao(environmentDaoConfig, this);
        localizationTypeDao = new LocalizationTypeDao(localizationTypeDaoConfig, this);
        environmentDao = new EnvironmentDao(environmentDaoConfig, this);

        registerDao(Environment.class, environmentDao);
        registerDao(LocalizationType.class, localizationTypeDao);
        registerDao(Environment.class, environmentDao);
    }
    
    public void clear() {
        environmentDaoConfig.getIdentityScope().clear();
        localizationTypeDaoConfig.getIdentityScope().clear();
        environmentDaoConfig.getIdentityScope().clear();
    }

    public EnvironmentDao getEnvironmentDao() {
        return environmentDao;
    }

    public LocalizationTypeDao getLocalizationTypeDao() {
        return localizationTypeDao;
    }

    public EnvironmentDao getEnvironmentDao() {
        return environmentDao;
    }

}
