package com.gppdi.ubipri.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.gppdi.ubipri.dao.Environment;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ENVIRONMENT".
*/
public class EnvironmentDao extends AbstractDao<Environment, Long> {

    public static final String TABLENAME = "ENVIRONMENT";

    /**
     * Properties of entity Environment.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Latitude = new Property(2, double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, double.class, "longitude", false, "LONGITUDE");
        public final static Property OperatingRange = new Property(4, double.class, "operatingRange", false, "OPERATING_RANGE");
        public final static Property Version = new Property(5, int.class, "version", false, "VERSION");
        public final static Property Distance = new Property(6, Double.class, "distance", false, "DISTANCE");
        public final static Property Shape = new Property(7, String.class, "shape", false, "SHAPE");
        public final static Property EnvironmentTypeId = new Property(8, long.class, "environmentTypeId", false, "ENVIRONMENT_TYPE_ID");
        public final static Property LocalizationTypeId = new Property(9, long.class, "localizationTypeId", false, "LOCALIZATION_TYPE_ID");
        public final static Property ParentId = new Property(10, Long.class, "parentId", false, "PARENT_ID");
    };

    private DaoSession daoSession;


    public EnvironmentDao(DaoConfig config) {
        super(config);
    }
    
    public EnvironmentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ENVIRONMENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"LATITUDE\" REAL NOT NULL ," + // 2: latitude
                "\"LONGITUDE\" REAL NOT NULL ," + // 3: longitude
                "\"OPERATING_RANGE\" REAL NOT NULL ," + // 4: operatingRange
                "\"VERSION\" INTEGER NOT NULL ," + // 5: version
                "\"DISTANCE\" REAL," + // 6: distance
                "\"SHAPE\" TEXT NOT NULL ," + // 7: shape
                "\"ENVIRONMENT_TYPE_ID\" INTEGER NOT NULL ," + // 8: environmentTypeId
                "\"LOCALIZATION_TYPE_ID\" INTEGER NOT NULL ," + // 9: localizationTypeId
                "\"PARENT_ID\" INTEGER);"); // 10: parentId
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_ENVIRONMENT_LATITUDE ON ENVIRONMENT" +
                " (\"LATITUDE\");");
        db.execSQL("CREATE INDEX " + constraint + "IDX_ENVIRONMENT_LONGITUDE ON ENVIRONMENT" +
                " (\"LONGITUDE\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ENVIRONMENT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Environment entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindDouble(3, entity.getLatitude());
        stmt.bindDouble(4, entity.getLongitude());
        stmt.bindDouble(5, entity.getOperatingRange());
        stmt.bindLong(6, entity.getVersion());
 
        Double distance = entity.getDistance();
        if (distance != null) {
            stmt.bindDouble(7, distance);
        }
        stmt.bindString(8, entity.getShape());
        stmt.bindLong(9, entity.getEnvironmentTypeId());
        stmt.bindLong(10, entity.getLocalizationTypeId());
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.bindLong(11, parentId);
        }
    }

    @Override
    protected void attachEntity(Environment entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Environment readEntity(Cursor cursor, int offset) {
        Environment entity = new Environment( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getDouble(offset + 2), // latitude
            cursor.getDouble(offset + 3), // longitude
            cursor.getDouble(offset + 4), // operatingRange
            cursor.getInt(offset + 5), // version
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // distance
            cursor.getString(offset + 7), // shape
            cursor.getLong(offset + 8), // environmentTypeId
            cursor.getLong(offset + 9), // localizationTypeId
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10) // parentId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Environment entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setLatitude(cursor.getDouble(offset + 2));
        entity.setLongitude(cursor.getDouble(offset + 3));
        entity.setOperatingRange(cursor.getDouble(offset + 4));
        entity.setVersion(cursor.getInt(offset + 5));
        entity.setDistance(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setShape(cursor.getString(offset + 7));
        entity.setEnvironmentTypeId(cursor.getLong(offset + 8));
        entity.setLocalizationTypeId(cursor.getLong(offset + 9));
        entity.setParentId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Environment entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Environment entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEnvironmentDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLocalizationTypeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getEnvironmentDao().getAllColumns());
            builder.append(" FROM ENVIRONMENT T");
            builder.append(" LEFT JOIN ENVIRONMENT T0 ON T.\"ENVIRONMENT_TYPE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN LOCALIZATION_TYPE T1 ON T.\"LOCALIZATION_TYPE_ID\"=T1.\"_id\"");
            builder.append(" LEFT JOIN ENVIRONMENT T2 ON T.\"PARENT_ID\"=T2.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Environment loadCurrentDeep(Cursor cursor, boolean lock) {
        Environment entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Environment environment = loadCurrentOther(daoSession.getEnvironmentDao(), cursor, offset);
         if(environment != null) {
            entity.setEnvironment(environment);
        }
        offset += daoSession.getEnvironmentDao().getAllColumns().length;

        LocalizationType localizationType = loadCurrentOther(daoSession.getLocalizationTypeDao(), cursor, offset);
         if(localizationType != null) {
            entity.setLocalizationType(localizationType);
        }
        offset += daoSession.getLocalizationTypeDao().getAllColumns().length;

        Environment parent = loadCurrentOther(daoSession.getEnvironmentDao(), cursor, offset);
        entity.setParent(parent);

        return entity;    
    }

    public Environment loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Environment> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Environment> list = new ArrayList<Environment>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Environment> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Environment> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
