package com.gppdi.ubipri.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCALIZATION_TYPE".
 */
public class LocalizationType {

    private Long id;
    /** Not-null value. */
    private String name;
    private double precision;
    /** Not-null value. */
    private String metric;

    public LocalizationType() {
    }

    public LocalizationType(Long id) {
        this.id = id;
    }

    public LocalizationType(Long id, String name, double precision, String metric) {
        this.id = id;
        this.name = name;
        this.precision = precision;
        this.metric = metric;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public double getPrecision() {
        return precision;
    }

    public void setPrecision(double precision) {
        this.precision = precision;
    }

    /** Not-null value. */
    public String getMetric() {
        return metric;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMetric(String metric) {
        this.metric = metric;
    }

}
